plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.fishtank.tv'
    compileSdk 34

    defaultConfig {
        applicationId "com.fishtank.tv"
        minSdk 22
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    flavorDimensions = ["site"]
    productFlavors {
        fishtank {
            dimension "site"
            applicationId "com.fishtank.tv"
            resValue "string", "app_name", "Fishtank TV"
            resValue "string", "home_url", "https://www.fishtank.live"
        }
        mde {
            dimension "site"
            applicationId "com.mde.tv"
            resValue "string", "app_name", "MDE TV"
            resValue "string", "home_url", "https://mde.tv"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'androidx.browser:browser:1.8.0'
}
